swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /authors:
    # binds a127 app logic to a route
    x-swagger-router-controller: add-author
    post:
      description: create author with parameters
      # used as the method name of the controller
      operationId: createAuthor
      parameters:
        - name: id
          in: body
          description: author id
          required: true
          type: integer
        - name: fname
          in: body
          description: author first name
          required: true
          type: string
        - name: lname
          in: body
          description: author last name
          required: true
          type: string  
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Author"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"        
            
            
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  Author:      
    type: object
    properties:
      id:
        type: integer
        required: true
        description: author id
      fname:
        type: string
        required: true
        description: Description of product.
      lname:
        type: string
        required: true
        description: Display name of product.
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
